apiVersion: apps/v1
kind: Deployment
metadata:
  name: zbl-ms-mofnnnriod
  namespace: cafbaeaimeuatprivate
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zbl-ms-mofnnnriod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zbl-ms-mofnnnriod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - aimc14
      containers:
      - env:
        - name: GRANT_SUDO
          value: "yes"
        - name: CHOWN_HOME
          value: "yes"
        - name: ZEBLOK_ACTION
          value: "true"
        - name: datalake_url
          value: http://datalake.intel.zeblok.com:9000
        - name: datalake_secret
          value: 10f10c0e814e8799d7d2e28599cb6be7f1ad5163
        - name: platform_url
          value: https://app.aime-uat.zeblok.com
        - name: DEFAULT_BUCKET
          value: 84c01a66fbae-abhinav
        - name: S3_BUCKET_NAME
          value: 84c01a66fbae-abhinav
        - name: BUCKET_TYPE
          value: MINIO
        - name: ACCOUNT_NAME
        - name: ACCOUNT_KEY
        - name: CLIENT_ID
        - name: CLIENT_SECRET
        - name: TENANT_ID
        - name: SUBSCRIPTION_ID
        - name: AWS_SECRET_KEY
        - name: AWS_ACCESS_KEY_ID
        - name: MLFLOW_SERVER_ALLOWED_HOSTS
          value: '*'
        image: hub.docker.zeblok.com/zeblok/mlflow-microservice:v1771940583.3.9.0
        imagePullPolicy: Always
        name: zbl-ms-mofnnnriod
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
            nvidia.com/gpu: "0"
          requests:
            cpu: "1"
            memory: 1Gi
            nvidia.com/gpu: "0"
      - env:
        - name: DEPLOYMENT_ENV
          value: aime-uat
        - name: NAME
          value: zbl-ms-mofnnnriod
        image: zeblok/lifecycle:dataqube
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - node start.js
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - node end.js
        name: lifecycle
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
